---
title: "Explore_Doublets"
author: "Vedran Franke"
date: "7/31/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  fig.width = 3, fig.height=3
  )
```

```{r}
suppressPackageStartupMessages({
  library(Seurat)  
  library(dplyr)
  library(ggplot2)
})

```


```{r, include=FALSE}
path = '/home/eulgen/doublet_removal/RDS_files/RNA_mixed_seu.RDS'
seu = readRDS(path)
```

```{r}
seu = FindClusters(seu, res=0.6)
```


```{r, fig.width =5}
seu@meta.data %>%
  cbind(seu@dr$umap@cell.embeddings) %>% 
  mutate(multiplet_info = case_when(
    multiplet_info != 'Multiplet' ~ 'Singlet',
    TRUE ~ 'Multiplet'
  )) %>% {
  ggplot(data = .,aes(UMAP1, UMAP2)) +
  geom_point(size=.5, color='lightgray') +
  geom_point(data = subset(., multiplet_info == 'Multiplet'), size=.5, color='red') +
      facet_wrap(~multiplet_info, nrow=1)
}
  

```
```{r}
seu@meta.data %>%
  cbind(seu@dr$umap@cell.embeddings) %>% {
  ggplot(data = .,aes(UMAP1, UMAP2)) +
  geom_point(size=.5, color='lightgray') +
  geom_point(data = subset(., Bridge == 'Bridge'), size=.5, color='red')
}
```

```{r}
a = seu@meta.data %>%
  cbind(seu@dr$umap@cell.embeddings) %>%
  mutate(prods = multiplet_info == 'Multiplet' & UMAP2 > 6 & UMAP2 < 8 & UMAP1 < 1)
a  %>%{
  ggplot(data = .,aes(UMAP1, UMAP2)) +
  geom_point(size=.5, color='lightgray') +
  geom_point(data = subset(., prods), size=.5, color='red')
}
  
```
```{r}
a %>%
  dplyr::filter(multiplet_info == 'Multiplet') %>%
  dplyr::filter(UMAP2 > 6 & UMAP2 < 12 & UMAP1 < 1) %>% {
  ggplot(data = .,aes(prods, nGene)) +
  geom_boxplot() +
  scale_y_log10()
}


```

